title: <p align="center"> Poonam Sharma</p>
logo: /assets/img/poonam1.png

description:
  <p align="center">
  <a href="https://github.com/poona-sharma">GitHub</a>
  
  <br>   
  Experienced IT Professional with 10+ Years in Advanced Java, NLP, and Machine Learning.
  <br>
  </p>



theme: jekyll-theme-minimal
